export const funFacts = [
  "The world's oldest known recipe is for beer.",
  "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.",
  "The shortest war in history lasted just 38 to 45 minutes. It was between Britain and Zanzibar on August 27, 1896.",
  "Octopuses have three hearts. Two hearts pump blood to the gills, while the third circulates it to the rest of the body.",
  "The Hawaiian alphabet consists of only 12 letters: A, E, H, I, K, L, M, N, O, P, U, and W.",
  "Cows have best friends and can become stressed when they are separated.",
  "The Great Wall of China is not visible from space without aid, contrary to popular belief.",
  "The original name of Bank of America was Bank of Italy when it was founded in 1904.",
  "The total weight of ants on Earth is roughly equal to the total weight of humans.",
  "Leonardo da Vinci could write with one hand and draw with the other simultaneously.",
  "The average person spends six months of their life waiting for red lights to turn green.",
  "The oldest known musical instrument is a flute made from a vulture's wing bone, dating back over 40,000 years.",
  "Polar bears have black skin to absorb and retain heat from the sun.",
  "The dot above the lowercase 'i' and 'j' is called a 'tittle'.",
  "In Japan, there are over 1,500 earthquakes each year.",
  "The world's largest volcano, Mauna Loa in Hawaii, is also one of the most active.",
  "Bananas are berries, while strawberries are not.",
  "Cleopatra lived closer in time to the first Moon landing than to the construction of the Great Pyramid of Giza.",
  "Ketchup was originally sold as medicine in the 1830s.",
  "The shortest war in history was fought between two African nations, Chad and Libya, in 1987. It lasted just 6 hours.",
  "The oldest known sample of the smallpox virus dates back to 17th-century child remains found in Lithuania.",
  "The world's smallest mammal is the bumblebee bat, which weighs about the same as a penny.",
  "The fingerprints of a koala are so indistinguishable from humans that they have been confused at crime scenes.",
  "There are more possible iterations of a game of chess than there are atoms in the known universe.",
  "The first computer programmer was a woman named Ada Lovelace, who wrote the first algorithm intended to be processed by a machine.",
  "A flock of flamingos is called a 'flamboyance'.",
  "The shortest complete sentence in the English language is 'I am.'",
  "The average person will spend about six months of their life waiting in lines.",
  "The longest recorded flight of a chicken was 13 seconds.",
  "A day on Venus is longer than a year on Venus. It takes about 243 Earth days for Venus to rotate once on its axis, but it only takes about 225 Earth days for Venus to orbit the sun.",
  "The original name of the search engine 'Google' was 'Backrub'.",
  "The fingerprints of a koala are so indistinguishable from humans that they have been confused at crime scenes.",
  "The average person walks the equivalent of three times around the world in a lifetime.",
  "Astronauts cannot burp in space due to the absence of gravity. Instead, they may experience discomfort caused by the buildup of gas in their stomachs.",
  "The world's oldest known leather shoe, dating back over 5,500 years, was found in Armenia.",
  "The chances of getting struck by lightning are higher than the chances of winning the lottery.",
  "Giraffes have the same number of neck vertebrae as humans: seven.",
  "The national animal of Scotland is the unicorn.",
  "The sentence 'The quick brown fox jumps over the lazy dog' contains every letter of the English alphabet.",
  "Astronauts' height can increase by up to 2 inches when spending extended periods in space due to the absence of gravity compressing the spine.",
  "The world's largest recorded snowflake measured 15 inches in diameter.",
  "Turtles can breathe through their rear end.",
  "The original name for the butterfly was 'flutterby'.",
  "The average person produces enough saliva in their lifetime to fill two swimming pools.",
  "Banging your head against a wall for one hour burns about 150 calories.",
  "There is a town in Norway called Hell, and it occasionally freezes over.",
  "The national animal of India is the Bengal Tiger.",
  "The longest recorded flight of a chicken was 13 seconds.",
  "The shortest war in history was between Britain and Zanzibar on August 27, 1896. It lasted just 38 to 45 minutes.",
  "The smallest bone in the human body is the stapes bone in the ear, measuring about 2.8 millimeters.",
  "The average person will spend approximately 25 years sleeping in their lifetime.",
  "The Hawaiian alphabet consists of only 12 letters: A, E, H, I, K, L, M, N, O, P, U, and W.",
  "The chance of you dying on the way to buy a lottery ticket is higher than the chance of actually winning the lottery.",
  "The world's oldest known musical instrument is a bone flute dating back over 40,000 years.",
  "A cow gives nearly 200,000 glasses of milk in her lifetime.",
  "The world's largest desert, the Sahara, is larger than the entire United States.",
  "Penguins have only one mate for their entire life. They propose by giving their partner a pebble.",
  "The first known use of the word 'computer' was in 1613 and referred to a human occupation, not a machine.",
  "If you shuffle a standard deck of 52 playing cards, chances are that exact order has never before existed in the history of the universe.",
  "The longest word in the English language is pneumonoultramicroscopicsilicovolcanoconiosis.",
  "The Earth's oceans contain enough gold to cover the entire planet in a knee-deep layer if it were evenly distributed.",
  "The world's largest pumpkin weighed over 2,600 pounds (1,179 kilograms).",
  "Mosquitoes are attracted to people who have recently eaten bananas.",
  "The Great Wall of China is not visible from space without aid, contrary to popular belief.",
  "The tongue is the strongest muscle in the human body relative to its size.",
  "The average person blinks around 15-20 times per minute.",
  "The oldest known image of a dragon comes from a cave in Bhutan, dating back over 7,000 years.",
  "It is physically impossible for pigs to look up into the sky.",
  "The total weight of ants on Earth is roughly equal to the total weight of humans.",
  "A group of flamingos is called a 'flamboyance'.",
  "The world's largest snow maze covers over 30,000 square feet (2,787 square meters).",
  "A cat's nose print is unique, much like a human's fingerprint.",
  "Cleopatra lived closer in time to the first Moon landing than to the construction of the Great Pyramid of Giza.",
  "The average person spends six months of their life waiting for red lights to turn green.",
  "A 'jiffy' is an actual unit of time, equivalent to 1/100th of a second.",
  "The Hawaiian alphabet only has 13 letters.",
  "The average cloud weighs about 1.1 million pounds (500,000 kilograms).",
  "The world's oldest known recipe is for beer.",
  "The shortest war in history lasted just 38 to 45 minutes. It was between Britain and Zanzibar on August 27, 1896.",
  "Octopuses have three hearts. Two hearts pump blood to the gills, while the third circulates it to the rest of the body.",
  "The national animal of Scotland is the unicorn.",
  "The first oranges weren't actually orange. They were green.",
  "The longest English word without vowels is 'rhythm'.",
  "The world's smallest reptile, the Brookesia micra chameleon, can fit on the tip of a matchstick.",
  "If you could fold a piece of paper in half 42 times, it would reach the moon.",
  "The national animal of Australia is the red kangaroo.",
  "There are more possible iterations of a game of chess than there are atoms in the known universe.",
  "Cows have best friends and can become stressed when they are separated.",
  "A 'butt' was a medieval unit of measure for wine, equal to 126 gallons.",
  "The average person will spend approximately six months waiting at red lights.",
  "The world's smallest bird is the bee hummingbird, weighing about as much as a penny.",
  "The first recorded Olympic games took place in 776 BC in Olympia, Greece.",
  "The national animal of South Africa is the springbok.",
  "The average human dream lasts only 2 to 3 seconds.",
  "There are more possible iterations of a game of chess than there are atoms in the known universe.",
  "Snails can sleep for up to three years.",
  "The Great Barrier Reef in Australia is the largest living structure on Earth, visible even from outer space.",
  "The longest recorded flight of a chicken was 13 seconds.",
  "A group of pugs is called a 'grumble'.",
  "The chance of you dying on the way to buy a lottery ticket is higher than the chance of actually winning the lottery.",
  "The oldest known musical instrument is a flute made from a vulture's wing bone, dating back over 40,000 years.",
  "The first known use of the word 'meme' was in Richard Dawkins' 1976 book 'The Selfish Gene'.",
  "A bolt of lightning can reach temperatures hotter than the surface of the Sun.",
  "Tigers have striped skin, not just striped fur.",
  "The average person will walk the equivalent of three times around the Earth in their lifetime.",
  "The chance of being born on February 29th (Leap Day) is about 1 in 1,461.",
  "Owls can rotate their heads up to 270 degrees in either direction, but they cannot move their eyes.",
  "The oldest known photograph in existence was taken in 1826 or 1827 by Joseph Nicéphore Niépce.",
  "The average person takes about 23,000 breaths per day.",
  "Giraffes have the same number of neck vertebrae as humans: seven.",
  "The shortest war in history was fought between two African nations, Chad and Libya, in 1987. It lasted just 6 hours.",
  "The national animal of India is the Bengal Tiger.",
  "A crocodile cannot stick its tongue out.",
  "The average person spends about six months of their life waiting in lines.",
  "Ketchup was originally sold as medicine in the 1830s.",
  "A day on Venus is longer than a year on Venus. It takes about 243 Earth days for Venus to rotate once on its axis, but it only takes about 225 Earth days for Venus to orbit the sun.",
  "The average person will spend about 25 years sleeping in their lifetime.",
  "The dot above the lowercase 'i' and 'j' is called a 'tittle'.",
  "The national animal of Scotland is the unicorn.",
  "The world's largest recorded snowflake measured 15 inches in diameter.",
  "Turtles can breathe through their rear end.",
  "The original name for the butterfly was 'flutterby'.",
  "The average person produces enough saliva in their lifetime to fill two swimming pools.",
  "Banging your head against a wall for one hour burns about 150 calories.",
  "There is a town in Norway called Hell, and it occasionally freezes over.",
  "The national animal of India is the Bengal Tiger.",
  "The longest recorded flight of a chicken was 13 seconds.",
  "The smallest bone in the human body is the stapes bone in the ear, measuring about 2.8 millimeters.",
  "The average person will spend approximately 25 years sleeping in their lifetime.",
  "The Hawaiian alphabet consists of only 12 letters: A, E, H, I, K, L, M, N, O, P, U, and W.",
];
