export const Cuisines = {
  Burgers: "burgers",
  Pizza: "pizza",
  Italian: "italian_cuisine",
  Sushi: "sushi",
  Chinese: "chinese",
  Vietnamese: "vietnamese",
  Mexican: "mexican_cuisine",
  Mediterranean: "mediterranean_cuisine",
  Indian: "indian_cuisine",
  MiddleEastern: "middle_eastern_cuisine",
  VegetarianVegan: "vegetarian_vegan_cuisine",
  Seafood: "seafood",
  BreakfastBrunch: "breakfast_brunch",
  DessertsSweets: "desserts_sweets",
  CoffeeShopsCafes: "coffee_shops_cafes",
} as const;
