import { Cuisine } from "delivfree";

export type AppStackParamList = {
  PrivacyPolicy: undefined;
  Welcome: undefined;
  Login: undefined;
  ChangePassword: undefined;
  SignUp: undefined;
  Tabs: undefined;
  EditProfile: undefined;
  Settings: undefined | { drawer?: boolean };
  About: undefined;
  DeleteAccount: undefined;
  Home: undefined;
  Restaurants: { cuisine: Cuisine };
  RestaurantDetail: { restaurantId: string };
  EditVendorProfile: undefined;
  EditDriverProfile: undefined;
  VendorDriverSelect: undefined;
  Orders: undefined;
  Profile: undefined;
  Subscription: { locked?: true };
  StartSubscription: { locked?: true };
  Locations: undefined;
  AddressSearch: undefined;
  Drivers: undefined;
  Loading: undefined;
  DriverCode: undefined;
  DriverRegistration: undefined;
  VendorRegistration: undefined;
  Positions: undefined;
  Users: undefined;
  Vendors: undefined;
  VendorDetail: { vendor: string };
  DriverDetail: { driver: string };
  AdConfig: undefined;
  PositionsSearch: undefined;
  Licenses: undefined;
  Menus: { tab?: string };
  Checkout: undefined;
  Payouts: undefined;
  WebView: { uri: string };
  Payment: { clientSecret: string };
  CheckoutCart: undefined;
  Tips: undefined;
  VendorTermsAndConditions: undefined | { mobile?: boolean };
  ConsumerTermsAndConditions: undefined | { mobile?: boolean };
};
